#cloud-config
package_update: true
package_upgrade: false

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

write_files:
  - path: /tmp/postgres/.env
    permissions: '0600'
    content: |
      POSTGRES_USER=${postgres_user}
      POSTGRES_PASSWORD=${postgres_password}
      POSTGRES_DB=${postgres_db}
  - path: /tmp/postgres/docker-compose.yml
    encoding: b64
    content: ${docker_compose_content}

runcmd:
  # Format and mount the volume
  - mkfs.ext4 -F /dev/sdb
  - mkdir -p /data
  - mount /dev/sdb /data
  - echo '/dev/sdb /data ext4 defaults,noatime 0 2' >> /etc/fstab

  # Docker 볼륨 디렉토리 생성 및 파일 복사
  - mkdir -p /data/postgres
  - cp -a /tmp/postgres/.env /data/postgres/
  - cp -a /tmp/postgres/docker-compose.yml /data/postgres/

  # Install Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker

  # Install Docker Compose
  - curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

  # Start PostgreSQL
  - cd /data/postgres && docker-compose up -d
