version: '3.8'

services:
  postgres:
    image: postgres:17.2
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgresuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-postgresdb}
      POSTGRES_INITDB_ARGS: "--lc-collate=ko_KR.utf8"
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgresuser} -d ${POSTGRES_DB:-postgresdb}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
